### ISSUE TITLE
User Story: Include option to sign-up with Twitter

### ISSUE THREAD

**Issue by charlie-vf** [charlie-vf/first-agile-project#10]
In order to **sign-up** as a **runner**, I can **use my Twitter account**.

## **Acceptance Criteria**
- Acceptance Criteria 1: The option should be presented on the sign-up page
- Acceptance Criteria 2: The option should link to a login page for Twitter
- Acceptance Criteria 3: The option should redirect back to the Love Running site with the user logged in

## **Tasks**
  
- [ ] Add Twitter sign-up feature to sign-up page
- [ ] Ensure it redirects to Twitter link page then back again
- [ ] Ensure safe use of user details
- [ ] Test functionality
