### ISSUE TITLE
User Story: Include option to sing-up with Facebook

### ISSUE THREAD

**Issue by charlie-vf** [charlie-vf/first-agile-project#11]
In order to **sign-up** as a **runner**, I can **use my Facebook account**.

## **Acceptance Criteria**
- Acceptance Criteria 1: The option should be presented on the sign-up page
- Acceptance Criteria 2: The link should link to a login page for Facebook
- Acceptance Criteria 3: The link should redirect back to the Love Running site with the user logged in

## **Tasks**
  
- [ ] Add Facebook sign-up feature to sign-up page
- [ ] Ensure redirect to Facebook login and back
- [ ] Ensure safe use of user details
- [ ] Test functionality
