### ISSUE TITLE
User Story: Tag faces to names in gallery 

### ISSUE THREAD

**Issue by charlie-vf** [charlie-vf/first-agile-project#8]
In order to **build the community** as a **runner**, I can **tag runners I know in the gallery page**.

## **Acceptance Criteria**
- Acceptance Criteria 1: I should be able to 'tag' names to images in the gallery
- Acceptance Criteria 2: This should be visible to all members

## **Tasks**
  
- [ ] Add feature to tag other members in images
- [ ] Request permission from tagged users before name goes live
- [ ] Test between hover-feature and click-through
- [ ] Test functionality
