### ISSUE TITLE
User Story: Include Twitter feed to show runners' tweets

### ISSUE THREAD

**Issue by charlie-vf** [charlie-vf/first-agile-project#9]
In order to **feel part of a close-knit community** as a **runner**, I can **see other runners' tweets on the Love Running homepage**.

## **Acceptance Criteria**
- Acceptance Criteria 1: The Twitter widget should be easy to find
- Acceptance Criteria 2: The widget should be on the homepage
- Acceptance Criteria 3: The widget should be scrollable

## **Tasks**
  
- [ ] Adjust homepage html/css to include social media widget
- [ ] Ensure works across platforms
- [ ] Ensure requests user login if browser not already logged in to Twitter
- [ ] Test functionality
